### ISSUE TITLE
Trying to authorise but get error 403

### ISSUE THREAD

**Issue by Mikee1234K** [Farmer-Eds-Shed/Node-Red-Google-API-Flows#4]
The created Google OAuth2 node cretes a URL to authorise Node Red. Clicking on my account creates a error 403

![image](https://user-images.githubusercontent.com/72687610/203551925-03d989a1-2108-4350-97f1-7ba91b3feb46.png)

**Comment by Farmer-Eds-Shed** [comment]
Hi @Mikee1234K 
You just need to give yourself access in Google Console
![image](https://user-images.githubusercontent.com/63633329/203558184-e6092334-c6eb-4087-846a-14e6b3e8efb4.png)

**Comment by Farmer-Eds-Shed** [comment]
Hmm, not sure what else to say,
The error is generated by Google to say you haven't added the test user.
The message hasn't changed at all?
All spellings correct?
you haven't inadvertently created 2 apps in google console?

**Comment by Mikee1234K** [comment]
I tried creating a Node Red project, first for the google calendar pallette which did not work for me. Thats how I got here...
Along the way there are now 2 projects, Node Red and Node Red 2. I thought I deleted Node Red but it still seems to be there

![image](https://user-images.githubusercontent.com/72687610/203564923-f3b49de5-03ee-4785-a766-1c9ad8da09df.png)

**Comment by Mikee1234K** [comment]
Actually I just gor further. I could click through, and its now trying to open http://127.0.0.1:1880/endpoint/Google/oauth2?code=4/0AfgeXvsIM5r8xxxxxxx   'Unable to connect'

**Comment by Mikee1234K** [comment]
Nearly there... I imported the get/post flow. Not sure how to find/enter the calendar id into the credentials node

**Comment by Farmer-Eds-Shed** [comment]
Go to your calendar with a browser.
Under My calendars, select the 3 dots beside the calendar you want. 
settings and sharing
Integrate Calendar
calendar ID

**Comment by Mikee1234K** [comment]
OK got that. I entered the calendar address into 'private' in the credentials node. I left the to as msg.calendar. Injecting the calendar id in teh flow, I get a json parse error in teh html node, and other errors in the debug.
I guess that I have to enter something else in the credential node ?

**Comment by Mikee1234K** [comment]
I had the wrong ID. Its working now, but rather than giving me the next event(s) I have all my created events and when they were created in the objects. How would I get a list of the lets say events in the next month ?

**Comment by Farmer-Eds-Shed** [comment]
Honestly, you are somewhat on your own from here as that was out of the scope of my project, but no reason it can't be built on from here. I created this flow just to POST events from my farm management app to Google Calendar and don't have much need currently to read them through the API.

The developer API docs would be your next port of call, I think list with timeMax and timeMin parameters may have what you want, but bear in mind I've not tested it. 
https://developers.google.com/calendar/api/v3/reference/events/list

**Comment by Mikee1234K** [comment]
Not a problem, I appreciate your help. The developers page on your link looks interesting, but I think thats beyond my current capabilities. I might ask on the Node Red forum, that is probably the right place, I would think someone on there will have done something similar

**Comment by Farmer-Eds-Shed** [comment]
Hi @Mikee1234K, this just popped up on my phone's news feed, https://fusebit.io/blog/google-calendar-api-javascript/?utm_source=www.google.com&utm_medium=referral&utm_campaign=none

There is a JavaScript example near the end which I think may help and should be relatively straight forward to implement in a function node in Node-Red.

**Comment by Mikee1234K** [comment]
Hi, thanks for that. I'll need a quiet day to try and digest that. But yes it looks as if I can just copy and paste into a function node. In the meantime I have a query of my google calendar from my home automation system, which gives me my upcoming months events and birthdays. I ues Node Red to query my system, and then display... I'd rather do it native in NR if I can, but for the moment it works. I am learning a lot of Node Red by programming my dashboard for my system. Its a pretty steep but satisfying learning curve. I do find the NR help files pretty unhelpful for someone with no programming background. But there are a few youtube videos which are very helpful, also the forum is great

**Comment by Farmer-Eds-Shed** [comment]
Authorization issue resolved
